### PR TITLE
Port helper class from PTVS and expose as NuGet packages (fixes #8)

### LINKED ISSUE #8: Port helper class from PTVS
For PTVS we use [helper classes](https://github.com/Microsoft/PTVS/tree/master/Common/Tests/Utilities.UI/UI) for interacting with Visual Studio.

We should port the core pieces of this functionality into VSTestHost so that people do not need to reimplement it themselves.

### PR DESCRIPTION
**Pull request by OmerRaviv**

### CODE REVIEW

**Comment by zooba** [comment]
Sorry for taking so long to get back to this - timing wasn't great - but we're looking right now.

**Comment by zooba** [comment]
FYI, looking okay so far, but after we merge we'll do a bit of work around the build scripts. To make releases, we need to be able to sign the assemblies, and we'd also rather not be so noisy when a version of VS isn't available.

**Comment by OmerRaviv** [comment]
OK, great. 

BTW, I've just noticed I made the mistake of making these projects compile against .NET 4.6 - should've been .NET 4.5 for VS2012 support. Let me know if you want me to push a fix for that or if you'll just change it along the way.

**Comment by zooba** [comment]
IIRC we need to switch the framework based on VS version anyway, which should be in the common build settings files. If you want to add that in, go for it.

We're also going to restore the top-level `Build` directory, so if you want to revert the deletions there too feel free to do that.

**Comment by zooba** [comment]
Still working on this - lot of things going on that are keeping me from finishing it though.

**Comment by zooba** [comment]
I'm not going to waste your time on the few little things to fix - you've done plenty of helpful work here. Thanks!

**Comment by OmerRaviv** [comment]
Sorry for being unresponsive earlier - got very swamped at work.

Thank you very much for making these _awesome_ utilities! Now that the PR is in I'll do my part to evangelize and let people know that they exist :)

**Pull request merged**
