### PR TITLE
Hive fix

### PR DESCRIPTION
**Pull request by zooba**
Lots of line ending changes, sorry.
Main fix is to allow "Default" as a value for hive, since we can't actually tell the difference between empty and absent in runsettings files (in the old testsettings files we could see that it was present and empty).

### CODE REVIEW

**Comment by mousetraps** [comment]
@zooba I don't think this is the last time we'll normalize line endings thanks to this insane bug. 
http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/4160768-save-text-files-with-the-newline-convention-presen

Really what we need to do is convert everything to CRLF in one go, and only then will we stop dealing with it.

**Comment by sharwell** [comment]
@zooba @mousetraps I took care of it in #16.

**Comment by sharwell** [comment]
@zooba Feel free to use mine as a reference in order to correct your final commit. I see you changed 10 files, but there were a total of 13 that needed correction.

**Comment by zooba** [comment]
@sharwell What are the three files? I only found TesterTestAdapter.cs (the sln file should be treated as binary because some versions of the VS version switcher treat it as binary).

**Comment by zooba** [comment]
Also, unrelated to the line endings, my tests I ran at 5pm still failed even with the fix and I didn't have time to figure out exactly why. Nobody hit merge just yet :)

**Comment by zooba** [comment]
Okay, looks like runsettings files are still unsupported because VS doesn't actually load them. So we're still stuck on testsettings files or individual test properties for now.

**Comment by zooba** [comment]
Running well on our systems, so I'm making a release with these changes.

**Pull request merged**
